// <auto-generated />
namespace BigRock.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DropParent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropParent));
        
        string IMigrationMetadata.Id
        {
            get { return "201406111244365_DropParent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
